;赔钱机场专用
;设置规则标志位
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/LocalAreaNetwork.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Unbreak.list
surge_ruleset=🛑 全球拦截,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Hijacking.list
surge_ruleset=🛑 全球拦截,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Advertising.list
surge_ruleset=🎬 影视国际,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TvBox.list
surge_ruleset=🎬 影视优化,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TvBox_Emby_Optimize.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Global.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/PROXY.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/GlobalEX.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/GlobalMedia.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/DIRECT.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/MyDIRECT.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/China.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/NobyDa/Surge/Download.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TvBoxCn.list
surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=♻️ 自动选择`url-test`.*`https://i.ytimg.com/generate_204`500
custom_proxy_group=🇮🇳 印度节点`select`(印度)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🔄 故障转移`fallback`(美国阿什本02-0.1x|🇺🇸 美国阿什本05-0.1x|🇯🇵 日本高速01-0.1x)`https://www.gstatic.com/generate_204`300,latency-timeout=2000
custom_proxy_group=🔰 默认节点`select`🔄 故障转移`[]🇮🇳 印度节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎬 影视国际`select`🔄 故障转移`[]🇮🇳 印度节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎬 影视优化`select`🔄 故障转移`[]🇮🇳 印度节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]🔰 默认节点`[]🇮🇳 印度节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`🔄 故障转移`[]DIRECT`[]🇮🇳 印度节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 手动切换
;设置分组标志位
