;设置规则标志位
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/LocalAreaNetwork.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Unbreak.list
surge_ruleset=🛑 全球拦截,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Hijacking.list
surge_ruleset=🛑 全球拦截,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Advertising.list
surge_ruleset=📹 YouTube,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/YouTube.list
surge_ruleset=🎥 NETFLIX,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/Netflix.list
surge_ruleset=🔍️ Google,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Google.list
;surge_ruleset=📺 AbemaTV,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/AbemaTV.list
;surge_ruleset=🤖 OpenAI,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/OpenAI.list
surge_ruleset=💵 币圈交易,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/CoinTrade.list
surge_ruleset=💵 PayPal,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/PayPal.list
;surge_ruleset=📺 自定媒体,rules/ConnersHua/Surge/Ruleset/Media/Spotify.list
;媒体list名字清单https://github.com/tindy2013/subconverter/tree/master/base/rules/ConnersHua/Surge/Ruleset/Media
surge_ruleset=📲 电报吹水,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Telegram.list
surge_ruleset=🇬🇧 英国限区,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/UKWifiCalling.list
surge_ruleset=🇬🇧 英国限区,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/UKRestricted.list
surge_ruleset=🇺🇸 美国限区,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/USWifiCalling.list
surge_ruleset=🇺🇸 美国限区,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/USRestricted.list
surge_ruleset=🇺🇸 美国限区,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/OpenAI.list
;surge_ruleset=🌍 国外媒体,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/GlobalMedia.list
;surge_ruleset=🌏 港台媒体,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/HKMTMedia.list
surge_ruleset=🎬 影视国际,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TvBox.list
surge_ruleset=🎬 影视优化,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TvBox_Emby_Optimize.list
;surge_ruleset=🌏 其它媒体,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/OtherMedia.list
surge_ruleset=🇯🇵 日本媒体,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Adult.list
surge_ruleset=🇯🇵 日本媒体,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/Pornhub.list
surge_ruleset=🎥 Disney,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/DisneyPlus.list
;surge_ruleset=📺 TIDAL,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TIDAL.list
;surge_ruleset=📺 Spotify,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/Spotify.list
surge_ruleset=📹 HBO,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/HBO.list
;surge_ruleset=📹 HBO,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/HBO_GO_HKG.list
surge_ruleset=📹 HBO,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/OtherMedia.list
;surge_ruleset=📺 PikPak,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/PikPak.list
surge_ruleset=🍎 苹果服务,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Apple.list
surge_ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/MSServices.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Global.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/PROXY.list
surge_ruleset=🔰 默认节点,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/GlobalEX.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/DIRECT.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/MyDIRECT.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/China.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/NobyDa/Surge/Download.list
surge_ruleset=DIRECT,https://raw.githubusercontent.com/zptpower1/nash/myini/rules/ConnersHua/Surge/Ruleset/Media/TvBoxCn.list
surge_ruleset=DIRECT,[]GEOIP,CN
surge_ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|HONG|Hong|HGC|MO)
custom_proxy_group=🇨🇳 台湾节点`select`(台|新北|彰化|TW|Tai)
custom_proxy_group=🇸🇬 狮城节点`select`(新|狮城|SG|Singa)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap)
;custom_proxy_group=🇬🇧 英国节点`select`(伦敦|UK|GB)
custom_proxy_group=🇺🇲 美国节点`select`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=🚀 其他节点`select`GCX`^((?!新|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|MO|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US).)*$
;custom_proxy_group=🎥 奈非节点`select`(NF|解锁|Netflix|NETFLIX)`[]🚀 其他节点`[]🚀 手动切换`^((?!新|多伦多|哥伦布|纽约|弗里蒙特|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|MO|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap|京日|杭日|青日|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United.*?States).)*$
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🔰 默认节点`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📲 电报吹水`select`[]🇸🇬 狮城节点`[]🔰 默认节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🔰 默认节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🎥 NETFLIX`select`[]🇸🇬 狮城节点`[]🎥 奈非节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎥 NETFLIX`select`(NF|解锁|Netflix|NETFLIX)`[]🚀 其他节点`[]🚀 手动切换`^((?!新|多伦多|哥伦布|纽约|弗里蒙特|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|MO|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap|京日|杭日|青日|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United.*?States).)*$
custom_proxy_group=🔍️ Google`select`[]🔰 默认节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇸🇬 狮城节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=📺 AbemaTV`select`[]🇯🇵 日本节点`[]🔰 默认节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🤖 OpenAI`select`[]🔰 默认节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=📺 自定媒体`select`[]🔰 默认节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🌍 国外媒体`select`[]🔰 默认节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
;custom_proxy_group=🌏 港台媒体`select`[]DIRECT`[]🚀 其他节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点
custom_proxy_group=🎬 影视国际`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]DIRECT`.*
custom_proxy_group=🎬 影视优化`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]DIRECT`.*
;custom_proxy_group=🌏 其它媒体`select`[]🔰 默认节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🇯🇵 日本媒体`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换
custom_proxy_group=🎥 Disney`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换
;custom_proxy_group=📺 TIDAL`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换
;custom_proxy_group=📺 Spotify`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换
custom_proxy_group=📹 HBO`select`[]🇭🇰 香港节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换
;custom_proxy_group=📺 PikPak`select`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`^((?!新|多伦多|哥伦布|纽约|弗里蒙特|Jap|Tai|Singa|狮城|SG|港|HK|HONG|Hong|HGC|MO|台|新北|彰化|TW|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Jap|京日|杭日|青日|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United.*?States).)*$
custom_proxy_group=💵 PayPal`select`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点
custom_proxy_group=💵 币圈交易`select`[]🇨🇳 台湾节点`[]🚀 其他节点`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🇬🇧 英国限区`select`(伦敦|UK|GB)
custom_proxy_group=🇺🇸 美国限区`select`(波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US)
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]🔰 默认节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🔰 默认节点`[]DIRECT`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🚀 其他节点
;设置分组标志位
